# Generated by AI Code Generation Agent
# This Python program implements the following use case:
# Develop a C-like language interpreter comprising a parser, type checker, and code executor. The interpreter must execute simple programs, supporting basic data types (integers, booleans, strings), control structures (if-else, for, while loops), and functions, including recursion. It will have a main entry point interpreter_main(str) for programmatic use. Command-line execution will support running programs from a file, displaying language documentation via --syntax, and executing an embedded test suite via --test. I/O is restricted to stdin/stdout using native print(), read_int(), read_bool(), and read_str() commands. The interpreter must gracefully handle syntax and runtime errors. A TEST_PROGRAMS list, structured as dictionaries, will validate functionality, mocking inputs and comparing outputs. Test results (PASS/FAIL, error messages, total/passed counts) must be reported. An embedded LANGUAGE_SPECIFICATION markdown string will document the language.
# It shall meet the following goals:
# - Implement a C-like language interpreter with distinct parser, type checker, and execution stages.
# - Ensure the interpreter correctly processes and executes programs using integers, booleans, strings, if-else, for/while loops, and functions.
# - Implement interpreter_main(str) to execute program code, handling multi-line input.
# - Enable command-line execution of programs from a file path argument.
# - Provide print(), read_int(), read_bool(), and read_str() for stdin/stdout operations.
# - Gracefully handle syntax errors (e.g., missing semicolons, unmatched delimiters) and runtime errors (e.g., division by zero, type mismatches, undefined variables).
# - Prioritize handling for malformed expressions, division by zero, type mismatches in operations, undefined variables/functions, and invalid input for read_int()/read_bool.
# - All other common syntax and runtime errors should be caught and reported with clear, descriptive messages.
# - Develop a TEST_PROGRAMS list covering all language features, including recursion, complex expressions, and error conditions.
# - Ensure TEST_PROGRAMS is concise (under 100 programs), combining tests where possible, and contains no comments or unnecessary text.
# - Implement a test runner that executes TEST_PROGRAMS, mocks inputs, compares outputs, and reports PASS/FAIL status with error messages.
# - The test runner must print the total number of tests and the count of passed tests at completion.
# - Embed a LANGUAGE_SPECIFICATION markdown string documenting the language syntax and features.
# - Implement command-line --syntax flag to print LANGUAGE_SPECIFICATION to stdout and exit.
# - Implement command-line --test flag to run all tests defined in TEST_PROGRAMS.
# - ASSUMPTION: The C-like language syntax will be a simplified subset, including standard arithmetic, logical, and comparison operators.
# - ASSUMPTION: interpreter_main(str) will return None or an equivalent void type, as its primary action is execution and printing.
# - ASSUMPTION: Error messages for syntax and runtime errors should be descriptive and include line/column information if possible.
# - ASSUMPTION: The TEST_PROGRAMS list will be provided as a Python list of dictionaries.
# Models used: coder=gemini-2.5-flash, reviewer=gemini-2.5-flash, utility=gemini-2.5-flash-lite
# It required 10 coding rounds to complete.

import sys
import argparse
from tests import run_tests
from interpreter import interpreter_main

# Part 1: Language Specification
LANGUAGE_SPECIFICATION = """
# C-like Language Specification

This document outlines the syntax and features of the simplified C-like language interpreter.

## Data Types
- `int`: Integer numbers (e.g., `10`, `-5`).
- `bool`: Boolean values (`true`, `false`).
- `string`: String literals (e.g., `"hello world"`).
- `void`: Used for functions that do not return a value.

## Variables
Variables must be declared with a type before use.
Example: `int x;`, `bool is_active = true;`, `string name = "Alice";`

## Operators
### Arithmetic Operators
- `+`, `-`, `*`, `/`, `%` (addition, subtraction, multiplication, division, modulo)
### Relational Operators
- `==`, `!=`, `<`, `>`, `<=`, `>=` (equality, inequality, less than, greater than, less than or equal, greater than or equal)
### Logical Operators
- `&&` (AND), `||` (OR), `!` (NOT)
### Assignment Operator
- `=`

## Control Structures
### If-Else Statement
```c
if (condition) {
    // statements if condition is true
} else {
    // statements if condition is false
}
```
The `else` block is optional.

### For Loop
```c
for (initialization; condition; increment) {
    // loop body
}
```

### While Loop
```c
while (condition) {
    // loop body
}
```

## Functions
Functions can be declared with a return type and parameters. Recursion is supported.
```c
int add(int a, int b) {
    return a + b;
}

void main() {
    int result = add(5, 3);
    // ...
}
```
`void` indicates no return value.

## Built-in I/O Functions
- `print(expression)`: Prints the value of the expression to stdout.
- `read_int()`: Reads an integer from stdin.
- `read_bool()`: Reads a boolean (`true`/`false`) from stdin.
- `read_str()`: Reads a string from stdin.

## Comments
Single-line comments start with `//`.
Multi-line comments are enclosed in `/* ... */`.

## Error Handling
The interpreter provides descriptive error messages for:
- Syntax errors (e.g., missing semicolons, unmatched delimiters).
- Runtime errors (e.g., division by zero, type mismatches, undefined variables/functions, invalid input for `read_int`/`read_bool`).
"""

def main():
    """
    Main function for command-line execution.
    Handles --syntax, --test, and file execution.
    """
    parser = argparse.ArgumentParser(description="A C-like language interpreter.")
    parser.add_argument("file", nargs="?", help="Path to the program file to execute.")
    parser.add_argument("--syntax", action="store_true", help="Display language syntax documentation.")
    parser.add_argument("--test", action="store_true", help="Run the embedded test suite.")

    args = parser.parse_args()

    if args.syntax:
        print(LANGUAGE_SPECIFICATION)
        sys.exit(0)

    if args.test:
        success = run_tests()
        sys.exit(0 if success else 1)

    if args.file:
        try:
            with open(args.file, "r") as f:
                program_code = f.read()
            print(f"Executing program from '{args.file}'...")
            # interpreter_main returns output_capture and actual_error, but for CLI we just print
            _, error = interpreter_main(program_code)
            if error:
                print(f"Execution Error: {error}", file=sys.stderr)
                sys.exit(1)
        except FileNotFoundError:
            print(f"Error: File not found: {args.file}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"An error occurred while reading or executing the file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("No file provided. Use --syntax for documentation or --test to run tests.")
        parser.print_help()
        sys.exit(1)

if __name__ == "__main__":
    main()